name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Installation des dépendances
        run: |
          python -m venv venv  # Crée l'environnement virtuel
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV
          source venv/bin/activate  # Active l'environnement virtuel
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Exécution des tests unitaires
        run: |
          source venv/bin/activate  # Active l'environnement virtuel
          pytest tests/
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Installation de flake8
        run: |
          python -m venv venv  # Crée l'environnement virtuel
          source venv/bin/activate  # Active l'environnement virtuel
          pip install flake8

      - name: Définition du PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      - name: Vérification du style de code
        run: |
          source venv/bin/activate  # Active l'environnement virtuel
          flake8 .

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Installation de black
        run: |
          python -m venv venv  # Crée l'environnement virtuel
          source venv/bin/activate  # Active l'environnement virtuel
          pip install black

      - name: Formatage du code avec black
        run: |
          source venv/bin/activate  # Active l'environnement virtuel
          black --check .  # Vérifie si le code est formaté
          black .  # Formate effectivement le code
