name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Installation des dépendances
        run: |
          python -m venv venv
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Exécution des tests unitaires
        run: |
          source venv/bin/activate
          pytest tests/
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Installation de flake8
        run: pip install flake8

      - name: Définition du PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      - name: Vérification du style de code
        run: flake8 .

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Installation de black
        run: pip install black

      - name: Formatage du code avec black
        run: |
          source venv/bin/activate
          black --check .  # Vérifie si le code est formaté
          black .  # Formate effectivement le code
